import type { AgentHookPluginFileInstallStrategy } from "../agent-hook-installer.js";

// Both generations discover the same file. Their loaders select the entrypoint:
// OpenCode 1 calls server(); OpenCode 2 calls setup(). Keep their event contracts
// separate: V1 publishes status snapshots, V2 publishes execution transitions.
export const OPENCODE_PLUGIN_SOURCE = [
  "const V1_STATUS_EVENTS = {",
  '  busy: "session.status.busy",',
  '  retry: "session.status.retry",',
  '  idle: "session.status.idle",',
  "};",
  "",
  "const V2_EVENTS = {",
  '  "session.execution.started": "session.status.busy",',
  '  "session.execution.succeeded": "session.status.idle",',
  '  "session.execution.failed": "session.status.idle",',
  '  "session.execution.interrupted": "session.status.idle",',
  '  "permission.asked": "permission.asked",',
  '  "permission.replied": "permission.replied",',
  "};",
  "",
  "function q8idevaiEventForV1(event) {",
  "  const type = event.type;",
  '  if (type === "permission.asked") return "permission.asked";',
  '  if (type === "permission.replied") return "permission.replied";',
  '  if (type !== "session.status") return null;',
  "  return V1_STATUS_EVENTS[event.properties.status.type] ?? null;",
  "}",
  "",
  // CLI processes can finish out of order, especially for immediate failures.
  // Both entrypoints enqueue reports so an older busy report cannot overwrite idle.
  "let pendingHook = Promise.resolve();",
  "",
  "function runQ8iDevAIHook(event) {",
  "  if (!process.env.Q8IDEVAI_TERMINAL_ID) return;",
  "  pendingHook = pendingHook.then(async () => {",
  "    try {",
  '      const child = Bun.spawn(["q8idevai", "hooks", "opencode", event], {',
  '        stdin: "ignore",',
  '        stdout: "ignore",',
  '        stderr: "ignore",',
  "      });",
  "      await child.exited;",
  "    } catch {}",
  "  });",
  "  return pendingHook;",
  "}",
  "",
  "export default {",
  '  id: "q8idevai-terminal-activity",',
  "  server() {",
  "    return {",
  "      event: async ({ event }) => {",
  "        const q8idevaiEvent = q8idevaiEventForV1(event);",
  "        if (q8idevaiEvent) await runQ8iDevAIHook(q8idevaiEvent);",
  "      },",
  "    };",
  "  },",
  "  setup(ctx) {",
  "    const controller = new AbortController();",
  "    void (async () => {",
  "      for await (const event of ctx.event.subscribe({ signal: controller.signal })) {",
  "        const q8idevaiEvent = V2_EVENTS[event.type];",
  "        if (q8idevaiEvent) await runQ8iDevAIHook(q8idevaiEvent);",
  "      }",
  "    })().catch(() => {});",
  "    return () => controller.abort();",
  "  },",
  "};",
  "",
].join("\n");

export function createOpenCodePluginInstallStrategy(): AgentHookPluginFileInstallStrategy {
  return {
    kind: "plugin-file",
    configDir: "opencode",
    configDirBase: "xdg-config",
    configFile: "plugins/q8idevai-terminal-activity.js",
    configDirEnvOverride: "OPENCODE_CONFIG_DIR",
    hookMarker: "q8idevai hooks opencode",
    source: OPENCODE_PLUGIN_SOURCE,
  };
}
